export abstract class ContactileGripperSetParametersProgConstants{
    static commandOpt = [      "BIAS",            "RESET_PARAMS",           "PC_SET_VEL",         "FF_SET_VEL",          "FF_SET_FORCE",             "DF_SET_VEL",           "DF_SET_EXF",           "DF_DYN_EXF_EN",         "DF_DYN_EXF_DIS",          "DF_SET_SHEARG",            "DF_SET_TORQG"];
    static commandIsArg = [    false,              false,                   true,                 true,                  true,                       true,                   true,                   false,                   false,                     true,                       true];
    static commandArgMin = [   0,                  0,                       5.0,                  5.0,                   1.5,                        5.0,                    1.5,                    0,                       0,                         1.0,                        0.0];
    static commandArgMax = [   0,                  0,                       334.0,                167.0,                 30.0,                       167.0,                  15.0,                   0,                       0,                         3.0,                        2000.0];
    static commandArgUnits = [ "",                 "",                      "mm/s",               "mm/s",                "N",                        "mm/s",                 "N",                    "",                      "",                        "",                         ""];
    static commandArgDef = [   0,                  0,                       334.0,                167.0,                 0,                          167.0,                  5.0,                    0,                       0,                         1.2,                        0.0];
    static commandRpcStr = [   "gripper_bias",    "gripper_reset_params",   "gripper_pc_set_vel",  "gripper_ff_set_vel", "gripper_ff_set_force",     "gripper_df_set_vel",   "gripper_df_set_exf",   "gripper_df_dyn_exf_en", "gripper_df_dyn_exf_dis",  "gripper_df_set_shearg",    "gripper_df_set_torqg"];
    static commandRetVar = [   "g_returnStatus",   "g_returnStatus",        "g_returnStatus",     "g_returnStatus",      "g_returnStatus",           "g_returnStatus",       "g_returnStatus",       "g_returnStatus",       "g_returnStatus",           "g_returnStatus",           "g_returnStatus"];
}